name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/ApiCoreApi
      
    - name: dotnet teste
      run: dotnet test
      
    - uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/ApiCoreApi/appsettings.json'
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.STRING_CNN }}
        AppSettings.Secret: ${{ secrets.TOKEN_SECRET }}
        DropBoxAccessToken: ${{ secrets.DROPBOX_TOKEN }}
        KissLog.OrganizationId: ${{ secrets.KISSLOG_ORGANIZATION }}
        KissLog.ApplicationId: ${{ secrets.KISSLOG_APPLICATION }}
        

    - name: Azure Login
      uses: azure/login@v1.1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: "ApiCoreApi"
        slot-name: "production"
        package: ${{env.DOTNET_ROOT}}/ApiCoreApi
